title: Book Clubs Lycée Georges Sand
email: lyc.sand.club.informatique@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Club Informatique du Lycée Georges Sand | Retrouvez tous vos clubs préférés au Lycée Georges Sand.
# uncomment for github pages utilisation
baseurl: /book-clubs # the subpath of your site, e.g. /blog
url: https://lyc-sand.github.io/book-clubs # the base hostname & protocol for your site, e.g. http://example.com
# uncomment for local utilisation and build
# baseurl:
# url:
twitter_username: LyceeSandDomont
github_username:  lyc-sand

markdown: kramdown
permalink: club/:categories/about
